### ISSUE TITLE
CLI: Add option to purge environment token variables and database.

### ISSUE THREAD

**Issue by ExtremelyRyan** [ExtremelyRyan/bytecloak-rs#35]
users may want the ability to purge their token from their env. variable after they have completed their tasks. we should be able to provide an easy method to do so.

database i am not so sure about, but we can semi-implement it for now

`crypt purge`
    - [ ] token
    - [ ] database

@JoshBenn what are the implications for adding this (purging db) feature?

**Comment by SublimeIbanez** [comment]
Other than losing access to all filecrypts, which is huge, none.
